### ISSUE TITLE
Easier to Use ARTIK IDE as Desktop IDE

### ISSUE THREAD

**Issue by ZhangHangdong** [codenvy/artik#138]
Through my past testing, I think it is better for us to easier to use ARTIK IDE as desktop IDE. 
So I think we should support the following 2 scenarios:

**Easy to install**
1> Provide a installation tool to one-click install ARTIK IDE to developer’s laptop/PC (Win7)
2> During installation and my daily development, I want to do nothing to virtualbox, docker … except the command of ARTIK IDE itself, because I am not a virtualization engineer.
![capture](https://cloud.githubusercontent.com/assets/20865878/18137086/e9bd1d56-6f5b-11e6-9272-c17b62f6b7ae.PNG)

**Developing without network**
1> After Installation, in my daily development, if I do nothing about update, I can use ARTIK IDE without network to internet. 
2> I have hold the IDE server in my laptop, I think I have no need to always connect with internet. 
![capture](https://cloud.githubusercontent.com/assets/20865878/18137123/fbfb1e00-6f5b-11e6-84b4-790eee01fb4b.PNG)

**Comment by ZhangHangdong** [comment]
Any response?

**Comment by TylerJewell** [comment]
In the past, we supported a native platform installer for Eclipse Che 3.x. It had a number of challenges with it.  To perform a proper installation, all of the following needs to be true:
1: There are more than 15 different packages for Docker, so it would have to bundle the appropriate ones.
2: For the installer to be open source, there are limited packaging technologies that can be applied.
3: Once the installation is completed, the system would then need to pre-download certain docker images - for Eclipse Che, for the ARTIK stacks, and perhaps other stacks that users may want to have downloaded. 
4: To have a proper double click of an icon that appears on the Windows desktop, we'd need to build and package an electron client. The user would use the electron client as their desktop window instead of regular Chrome.  The electron client would then have the intelligence to start / stop the Che server in the background.
5: And then there would need to be appropriate uninstall packages, which would need to uninstall Che - and possibly Docker, too.

**Comment by eivantsov** [comment]
https://github.com/codenvy/artik-ide/issues/237

**Comment by eivantsov** [comment]
Fixed by releasing an installer for Win and Mac
