### ISSUE TITLE
Discover ARTIK from Eclipse che 

### ISSUE THREAD

**Issue by Connin** [codenvy/artik#269]
Hello,
I'm trying to Follow 
https://eclipse-che.readme.io/docs/samsung-artik-ide-getting-started
And
https://eclipse-che.readme.io/docs/artik-usb-connection-setup.

I'd like to let my ARTIK IDE to find my ARTIK board.

Since I do not have an additional Ethernet connection, I connected my ARTIK board to Wi-Fi.
![image](https://cloud.githubusercontent.com/assets/19319864/21333617/f7dd948c-c605-11e6-8070-0faa3febccfa.png)

After I put IP address in inet, I got an error message below.

![image](https://cloud.githubusercontent.com/assets/19319864/21333653/501b2d30-c606-11e6-83d6-e4b401081452.png)

I also tried to connect by USB by following this
https://eclipse-che.readme.io/docs/artik-usb-connection-setup.

but it seems ADB does not recognize my ARTIK board
![image](https://cloud.githubusercontent.com/assets/19319864/21333968/9664d0f0-c608-11e6-8a45-ed1776af5239.png)

I connected my ARTIK to Both USB and Micro USB.

Is there anything I can do to fix this issue?
It does not matter if I can connect to Wi-Fi or USB as long as ARTIK IDE can found my ARTIK board.

Thanks!

**Comment by eivantsov** [comment]
@Connin 

1. You need to enable USB discovery in VirtualBox - http://www.htpcbeginner.com/access-usb-drive-in-virtualbox-guest-os/
2. adb devices returned nothing for your Windows machine. Probablt wrong usb port. What happens if you connect your Android phone and run the same command?

3. Can you ssh into your VM?

`docker-machine ssh default`
`ssh root@$IP`

Will such a login attempt be a success?

4. Can you try sshing from the workspace? When in the IDE, in the terminal run:

`ssh root@$IP`

As to auto discovery in the IDE and a prompt to connect to a device, there was such a feature request but this feature will only work on Linux and Win/Mac with boot2docker (provided that VirtualBox can see host USB devices). New Docker for Windows and Mac do not support host USB devices in the VM, therefore there's no way to see them.

We will investigate arp-scan or smth similar to scan network for Artik devices

**Comment by Connin** [comment]
1. You are right, I followed https://eclipse-che.readme.io/docs/artik-usb-connection-setup again to 
enable USB in VM as shown in screenshot.
I restarted my ARTIK and VM after enabling USB.

![image](https://cloud.githubusercontent.com/assets/19319864/21372878/f47ba224-c6ce-11e6-9008-26133f78bbc1.png)

2. I have connected my android cellphone via USB and typed adb devices and below screenshot is what I saw. I connected both ARTIK and Android phone but I see only android cellphone.

![image](https://cloud.githubusercontent.com/assets/19319864/21373386/66e55b1c-c6d3-11e6-8cba-c80d359b0fa6.png)

3. I put ssh root@$IP in VM and it is the message I got. 
ssh: Could not resolve hostname : Name or service not known
![image](https://cloud.githubusercontent.com/assets/19319864/21373842/b58044fa-c6d6-11e6-9677-c453f92def2f.png)

I also did the same thing on my Windows cmd and the same result.
![image](https://cloud.githubusercontent.com/assets/19319864/21373848/bcaea938-c6d6-11e6-8c23-c219907d1f39.png)

4. Finally, I put the same ssh root@$IP in IDE as shown in the screenshot and I got the same error message.
ssh: Could not resolve hostname : Name or service not known

![image](https://cloud.githubusercontent.com/assets/19319864/21373647/6591d234-c6d5-11e6-9add-96b93552dd55.png)

Thanks,

**Comment by eivantsov** [comment]
`$IP` should be actual IP of your Artik device.

> I have connected my android cellphone via USB and typed adb devices and below screenshot is what I saw. I connected both ARTIK and Android phone but I see only android cellphone.

Artik IDE isn't involved at that point. Have you tried different USB ports? It should me mini USB, not micro. Also, try different USB ports on your laptop.

**Comment by Connin** [comment]
Hello, thank you for response.

I tried both cmd and ssh root@$IP in workspace.
Here is what I got.
![image](https://cloud.githubusercontent.com/assets/19319864/21409318/72163022-c78e-11e6-9d45-a147db6b45b6.png)

![image](https://cloud.githubusercontent.com/assets/19319864/21409326/7d0b26fe-c78e-11e6-898f-e0860b421194.png)

But when I tried to connect my ARTIK board and IDE by clicking ARTIK Icon as shown in the screenshot, I got following error message.
![image](https://cloud.githubusercontent.com/assets/19319864/21410908/27050094-c799-11e6-98d4-2664c7256690.png)

![image](https://cloud.githubusercontent.com/assets/19319864/21409680/655a9bc8-c790-11e6-9170-7a6563dc9ea8.png)

After I type ./ watcher& command into the Putty, adb finally recognize my ARTIK board as shown in screenshot. But manage ARTIK devices windows says "No USB devices found".
 As you have told me, I believe Artik IDE isn't involved at that point. I tried other USB ports but it still gives the same result.

![image](https://cloud.githubusercontent.com/assets/19319864/21411342/b23e569e-c79c-11e6-948d-45b57a34332b.png)

**Comment by eivantsov** [comment]
@Connin there's a bug in the latest release that prevents terminal from being launched on the device which impacts connection as well. It's fixed in current master.

As to USB auto discovery, if adb devices does not return anything when you execute this command in a workspace or the VM, no IP will be displayed in the manage connections dropdown.

**Comment by Connin** [comment]
Yes, I typed adb devices in workspace and it gives nothing. So I believe it means IDE does not access to my port for some reason that I do not know. 
![image](https://cloud.githubusercontent.com/assets/19319864/21442428/b7031906-c852-11e6-86ce-74c144b136b5.png)

I think I have to work on to connect my ARTIK device via Wi-Fi.  
How can I get that "current master"?

**Comment by eivantsov** [comment]
@Connin as to adb, you should first make sure that the VM can recognize your USB devices. Looks like Android phone can be seen but not Artik board. I cannot say right now why it happens especially since Artik cannot be discovered by adb through the command line. We are re-thinking board discovery mechanism in favor or network scan since adb may be unreliable in some cases.

As to trying the latest Artik IDE, please run this command:

`docker run -ti -v /var/run/docker.sock:/var/run/docker.sock -v /c/users/UserName/artik:/data codenvy/artik-cli:nightly start`

Please note that `/c/users/kyle.bae/artik` should be an existing path on your Win machine. Create artik directory in your user dir. This is where all of Artik data and config will be persisted.

**Comment by Connin** [comment]
when I type it in cmd, I got this message.
docker run -ti -v /var/run/docker.sock:/var/run/docker.sock -v /c/users/kyle.bae/artik:/data codenvy/artik-cli:nightly start

![image](https://cloud.githubusercontent.com/assets/19319864/21534371/d64e3670-cd1a-11e6-8951-3564185a0f76.png)

Unable to find image 'codenvy/artik-cli:nightly' locally
Pulling repository docker.io/codenvy/artik-cli
docker: Error while pulling image: Get https://index.docker.io/v1/repositories/codenvy/artik-cli/images: x509: certificate signed by unknown authority.
See 'docker run --help'.

I found that
docker run -p 8080:8080 -v /C/Users/kyle.bae/artik-ide:/data --rm -t -v/var/run/docker.sock:/var/run/docker.sock codenvy/artikide start
this command still works.

Is there any difference which cause this error?

Thanks.

**Comment by eivantsov** [comment]
@Connin can you manually run `docker pull codenvy/artik-cli:nightly`?

**Comment by Connin** [comment]
Hello,

I have tried 
docker pull codenvy/artik-cli:nightly
and

I believe I got the same error message
![image](https://cloud.githubusercontent.com/assets/19319864/21705073/6cdd4592-d372-11e6-90bc-7cd585844b2a.png)

**Comment by eivantsov** [comment]
@Connin I think you need to destroy and recreate your docker machine.

**Comment by eivantsov** [comment]
@Connin we're planning to implement a new mechanism of device discovery which will be network based. I'll update this issue when it's done.

**Comment by eivantsov** [comment]
Fixed by https://github.com/codenvy/artik/issues/343
